name: Secret

on:
  workflow_dispatch:

jobs:
  secret:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch secret
        run: |
          touch ${{ github.workspace }}/.npmrc
          echo ${{ secrets.SUPER_TOP_SECRET }} >> ${{ github.workspace }}/.npmrc
          cat ${{ github.workspace }}/.npmrc
